name: rise-environment
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - pip==19.2.3
  - pip:
    - altair==4.1.0
    - bokeh==2.0.1
    - branca==0.4.0
    - configparser==5.0.0
    - crayons==0.3.0
    - descartes==1.1.0
    - flask-cors==3.0.8
    - folium==0.10.1
    - markdown==3.2.1
    - mizani==0.6.0
    - palettable==3.3.0
    - panel==0.9.5
    - param==1.9.3
    - plotly==4.6.0
    - plotnine==0.6.0
    - py4j==0.10.7
    - pyct==0.4.6
    - pyspark==2.4.5
    - pyviz-comms==0.7.4
    - retrying==1.3.3
    - rise==5.6.1
    - selenium==3.141.0
    - typing-extensions==3.7.4.2
    - vega-datasets==0.8.0
    - webdriver-manager==2.3.0
